# Generated by Django 3.1 on 2020-08-19 04:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('manager_email_address', models.CharField(default='', max_length=50)),
                ('type_of_participant', models.CharField(choices=[('BAND', 'Band'), ('CARRIAGE', 'Carriage')], default='BAND', max_length=8)),
                ('foundation_date', models.DateTimeField()),
                ('registered_date', models.DateTimeField(default=datetime.datetime(2020, 8, 19, 4, 39, 46, 228571, tzinfo=utc))),
                ('order', models.IntegerField(default=1)),
            ],
        ),
    ]
